name: presinter
description: Tools for creating and running interactive presentations.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  auth_for_perception: ^0.0.0-a1
  core_of_perception: ^0.0.0-a1
  error_handling_for_perception: ^0.0.0-a1
  inspector_for_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  navigation_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

  # firestore
  firestore_service_interface: ^0.0.0-a1
  firestore_service_flutterfire: ^0.0.0-a1

  # types
  types_for_auth: ^0.0.0-a1
  
  collection: ^1.17.1
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  enspyr_lints: ^0.0.0-a1
  test_utils_for_perception: ^0.0.0-a1
